---
- hosts: localhost
  roles:
      - role: kurron.hashicorp
      - role: kurron.software-developer
      - role: kurron.resilio-sync
      - role: kurron.virtualbox

- name: Install Required Packages
  hosts: localhost
  become: yes
  tasks:
     - package:
           name: "{{item}}"
           state: present
       with_items:
       - "tree"

