---
- hosts: localhost
  roles:
      - { role: kurron.hashicorp, tags: [ 'hashicorp' ] }
      - role: kurron.software-developer
      - role: kurron.resilio-sync
      - role: kurron.virtualbox

- name: Install Desired Packages
  hosts: localhost
  become: yes
  tasks:
      - dnf:
          name: "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-24.noarch.rpm"
          state: present
      - dnf:
            name: "{{item}}"
            state: present
        with_items:
        - "tree"
        - "gnome-tweak-tool"
        - "vlc"
        - "gimp"
        - "youtube-dl"
        - "unzip"
        - "qbittorrent"
        - "pidgin"
        - "gnome-music"
        - "filezilla"
        - "grsync"

- name: Mount NAS
  hosts: localhost
  become: yes
  tasks:
      - lineinfile:
            dest: /etc/hosts
            line: "{{ item }}"
        with_items:
          - '192.168.1.227 stargate'
          - '192.168.1.229 atlantis'
          - '192.168.1.233 bifrost'
          - '192.168.1.234 nas'
          - '192.168.1.235 alfheim'
          - '192.168.1.236 midgard'
          - '192.168.1.240 vanaheim'
          - '192.168.1.250 asgard'
      - file:
          path: "/mnt/nas"
          state: directory
      - dnf:
          name: nfs-utils
          state: present
      - mount:
          name: "/mnt/nas"
          src: "nas:/media"
          fstype: nfs
          opts: ro
          state: mounted
