---
- hosts: all
  roles:
      - role: kurron.docker-host
      - role: kurron.hashicorp
      - {
            role: kurron.operations,
            operations_loggly_token: "{{ lookup('env','LOGGLY_TOKEN') }}",
            operations_loggly_tag: "basement",
            operations_datadog_api_key: "{{ lookup('env','DATADOG_TOKEN') }}"
        }
      - role: kurron.plex
      - role: kurron.resilio-sync
      - role: kurron.rsync

- name: Mount NAS
  hosts: all
  become: True
  tasks:
      - lineinfile:
            dest: /etc/hosts
            line: "{{ item }}"
        with_items:
          - '192.168.1.222 batcave'
          - '192.168.1.227 stargate'
          - '192.168.1.229 atlantis'
          - '192.168.1.233 bifrost'
          - '192.168.1.234 nas'
          - '192.168.1.236 openvpn'
      - file:
          path: "/mnt/nas"
          state: directory
      - apt:
          name: nfs-common
          state: present
      - mount:
          name: "/mnt/nas"
          src: "nas:/media"
          fstype: nfs
          opts: ro
          state: mounted
